Repository DatosAnalyticos/Memry, pull requests merged in 2020-02, with the labels that each got.

#8 Developer Documentation
  CHANGELOG.md
  README.md
Labels: 📖 documentation

#9 Automate Testing of ReactJS through NodeJS
  .github/workflows/nodejs.yml
Labels: 🛠 enhancement, 🤖 automation

#12 Changes the current theme to IOS
  src/App.tsx
Labels: 🛠 enhancement

#13 Refactoring the ReadMe title
  README.md
Labels: 📖 documentation, 🛠 enhancement

#16 Spaces to Tab Indentation + React Build Automated Test
  .github/workflows/nodejs.yml
  LICENSE
  capacitor.config.json
  ionic.config.json
  package.json
  public/index.html
  public/manifest.json
  src/App.test.tsx
  src/App.tsx
  src/components/ExploreContainer.css
  src/components/ExploreContainer.tsx
  src/global.css
  src/pages/Home.css
  src/pages/Home.tsx
  src/serviceWorker.ts
  src/theme/variables.css
  tsconfig.json
Labels: 🛠 enhancement

#19 Default Pull Request Template
  .github/pull_request_template.md
Labels: 🛠 enhancement, 🤖 automation

#20 Do automated testing on `pull_request.branches.dev` only
  .github/workflows/nodejs.yml
Labels: 🛠 enhancement, 🤖 automation

#21 Auto-publish release when merging to master branch
  .github/workflows/release.yml
  .releaserc.js
  package-lock.json
  package.json
Labels: 🛠 enhancement, 🤖 automation

#25 Include `semantic-release` library on NPM
  package-lock.json
  package.json
Labels: 🔥 hotfix, 🤖 automation

#30 Pull Request Merge Event for Auto-Release
  .github/workflows/release.yml
Labels: 🛠 enhancement, 🤖 automation

#31 `Play` section
  src/App.jsx
  src/App.test.jsx
  src/components/ExploreContainer.tsx
  src/index.jsx
  src/pages/Completed.jsx
  src/pages/Home.jsx
  src/pages/Play.css
  src/pages/Play.jsx
Labels: 🛠 enhancement

#33 Broken XML-based format of the documentation
  README.md
Labels: 📖 documentation

#34 Home page section
  src/components/ExploreContainer.css
  src/pages/Home.css
  src/pages/Home.jsx
Labels: 🛠 enhancement

#40 Release new update every time we push on the `dev`
  .github/workflows/release.yml
Labels: 🤖 automation
